#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH --ntasks=1
#SBATCH --job-name=IOBC_TEST
#SBATCH --account=akwaters
#SBATCH --output=IOBC_TEST.%j
#SBATCH --no-requeue
#SBATCH -p debug
###SBATCH -p t1standard
###SBATCH -t 44:00:00

cd $SLURM_SUBMIT_DIR
. /usr/share/Modules/init/bash
module purge
module load slurm/22.05.4
#module load intel/2023a
module load foss/2022a
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/kshedstrom/intel_23/lib
module load netCDF-Fortran/4.5.4
#module list

rm ocean.stats.gnu seaice.stats.gnu
#rm ocean.stats.intel* seaice.stats.intel

#conda activate snowy

#
#  Prolog
#
echo " "
echo "++++ Chinook ++++ $PGM_NAME began:    `date`"
echo "++++ Chinook ++++ $PGM_NAME hostname: `hostname`"
echo "++++ Chinook ++++ $PGM_NAME uname -a: `uname -a`"
echo " "
TBEGIN=`echo "print time();" | perl`

#rm diag_table.yaml
#diag-table-to-yaml -f diag_table

mpirun -np $SLURM_NTASKS --mca mpi_paffinity_alone 1 /import/c1/AKWATERS/kshedstrom/MOM6_22/build/gnu/ocean_only/repro/MOM6
#mpirun -np $SLURM_NTASKS --mca mpi_paffinity_alone 1 /import/c1/AKWATERS/kshedstrom/MOM6_22/build/gnu/ocean_only/debug/MOM6

#
#  Epilog
#
TEND=`echo "print time();" | perl`
echo " "
echo "++++ Chinook ++++ $PGM_NAME pwd:      `pwd`"
echo "++++ Chinook ++++ $PGM_NAME ended:    `date`"
echo "++++ Chinook ++++ $PGM_NAME walltime: `expr $TEND - $TBEGIN` seconds"
